apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: microbot-ingress
spec:
 rules:
   - host: microbot.10.168.36.219.xip.io
     http:
       paths:
         - path: /
           backend:
             serviceName: microbot
             servicePort: 80
